# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-09-08 17:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='key',
            field=models.CharField(default='A', max_length=4),
            preserve_default=False,
        ),
    ]
