# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-09-24 22:27
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('problems', '0007_auto_20170911_2208'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='users_solved',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
